### ISSUE TITLE
Create a list of resources

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/secure-git-guide#14]
- [Terminal User Interface for GnuPG](https://github.com/orhun/gpg-tui)

**Comment by josecelano** [comment]
- https://resources.github.com/downloads/GitHubAdvanced%20SecurityEbook.pdf

**Comment by josecelano** [comment]
- http://www-cs-students.stanford.edu/~blynn/gitmagic/

**Comment by cgbosse** [comment]
OK I will include it in the  List
