### ISSUE TITLE
`https://secure-git.guide/` returns 404

### ISSUE THREAD

**Issue by da2ce7** [Nautilus-Cyberneering/secure-git-guide#57]
Somehow, overnight, the custom url doesn't load. At least for me.

Hmm.

**Comment by josecelano** [comment]
I think this could be the reason:

https://github.community/t/github-forgets-about-my-custom-domain-every-time-i-update-the-website/10246

We have to keep this file:

https://github.com/Nautilus-Cyberneering/secure-git-guide/blob/gh-pages/CNAME
