### ISSUE TITLE
Move Secure Git Guide to Svelet.Kit

### ISSUE THREAD

**Issue by da2ce7** [nautilus-cyberneering/secure-git-guide#68]
Use consistent infrastructure as https://github.com/torrust/torrust-website

**Comment by josecelano** [comment]
@grmbyrn has created a [new version in SvelteKit](https://github.com/nautilus-cyberneering/secure-git-guide/pull/69). Now we have to:

- [] Remove the old version and make the `secure-git-guide-branch` to the root folder.
- [] Copy info from old README to the new one.
- [] Setup workflow for deployment to GitHub pages.
- [] Install the new version of MegaLinter and fix errors.

**Comment by grmbyrn** [comment]
I have done the following this morning: 
- [x] Remove the old version and make the secure-git-guide-branch to the root folder.
 - [x] Copy info from old README to the new one.
 - [ ] Setup workflow for deployment to GitHub pages.
 - [ ] Install the new version of MegaLinter and fix errors.

**Comment by josecelano** [comment]
> I have done the following this morning:
> 
> * [x]  Remove the old version and make the secure-git-guide-branch to the root folder.
> * [x]  Copy info from old README to the new one.
> * [ ]  Setup workflow for deployment to GitHub pages.
> * [ ]  Install the new version of MegaLinter and fix errors.

OK @grmbyrn, are you going to open a PR?
