### ISSUE TITLE
Continue using MegaLinter?

### ISSUE THREAD

**Issue by josecelano** [nautilus-cyberneering/secure-git-guide#71]
Hi @da2ce7 @grmbyrn , this [PR](https://github.com/nautilus-cyberneering/secure-git-guide/pull/69) is pending to merge because MegaLinter check is not passing.

Do you think we should continue using MegaLinter in this project?

**Comment by cgbosse** [comment]
What are the advantages and the disadvantages?

**Comment by josecelano** [comment]
> What are the advantages and the disadvantages?

### Pros

- **Code Quality Assurance**: MeGaLinter helps maintain high code quality by checking for syntax errors, coding standards, and potential bugs. This ensures that code in pull requests adheres to project standards.

- **Automated Code Review**: It automates part of the code review process, saving time for developers. They can focus on more complex aspects of the code rather than basic style or formatting issues.

- **Consistency in Codebase**: Ensures consistency in coding style across multiple contributors. This is particularly useful in open-source projects or teams with diverse coding habits.

- **Early Detection of Issues**: Identifies problems early in the development cycle, reducing the cost and effort of fixing them later.

- **Integrates with CI/CD Pipelines**: Can be easily integrated into Continuous Integration/Continuous Deployment (CI/CD) pipelines, streamlining the development process.

- **Customizable Rules**: Offers flexibility to customize rules based on the project's specific needs, allowing teams to enforce their own coding standards.

### Cons

- **Initial Setup and Configuration**: Requires initial effort to set up and configure according to the project's needs. This might be time-consuming, especially for complex projects.

- **Learning Curve**: Developers need to familiarize themselves with the linter rules and configuration, which might have a learning curve.

- **Potential for False Positives/Negatives**: Like any automated tool, it may sometimes flag false positives (identifying non-issues as errors) or miss certain issues (false negatives).

- **Overhead on Build Process**: It can add additional time to the build process, especially if the project is large or the linter is configured to perform extensive checks.

- **Possible Resistance from Developers**: Some developers might resist strict linting rules, perceiving them as restrictive or counterproductive to their coding style.

- **Maintenance of Linter Configuration**: As the project evolves, the linter configuration may need regular updates to stay relevant, which requires ongoing maintenance.

### Conclusion

For me, it is worth having it because I learn a lot from linters even if it's a pain to set them up and to maintain them. But I also think that maybe we do not need all of them. So the question for me is which ones are valuable for us in this repo?

**Comment by cgbosse** [comment]
As a side note I think this question can become a good blogpost following my double objective philosophy.

**Comment by grmbyrn** [comment]
I haven't had experience with linters so I am going through some resources so I can get it to pass the check. The pros and cons lists are very useful.

**Comment by nvuillam** [comment]
If you find some linters too noisy, don't forget that you can disable or make them not blocking ;)

If you stop using MegaLinter, you should make sure to use something else, because a repo without linting & security in 2023 is not a good way to provide quality & safety ^^

**Comment by josecelano** [comment]
> If you find some linters too noisy, don't forget that you can disable or make them not blocking ;)
> 
> If you stop using MegaLinter, you should make sure to use something else, because a repo without linting , security & spell checks in 2023 is not a good way to provide quality & safety ^^

I just wanted to confirm all members agree on using it so we all take ownership. We are going to install the new version for the new version of the site using Svelte.

https://github.com/nautilus-cyberneering/secure-git-guide/issues/74
